# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Perks of being a Wallflower', 'Perks of being a Wallflower'), ('All the bright places', 'All the bright places')], max_length=100)),
            ],
        ),
    ]
